### ISSUE TITLE
Undefined symbol error is occurred in zetta with Intel Compiler Environment

### ISSUE THREAD

**Issue by FIshikawa** [todo-group/pycxx#1]
In zetta, if the test program is compiled by the intel compiler, I get the following error.

      [fumihiro@zetta build]$ ./pytest.py 
      Traceback (most recent call last):
       File "./pytest.py", line 2, in <module>
          import cxxmod
      ImportError: /home/fumihiro/pycxx/boost/build/cxxmod.so: undefined symbol:_ZN5boost6python6detail12gcc_demangleEPKc   

The gcc environment  can avoid the error.
I didn't figure out the causes.

**Comment by wistaria** [comment]
In my environment,
```
source /opt/materiapps/env.sh
cd $HOME/pycxx/boost/build
cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc ..
make
./pytest.py
```
works perfectly. How does the output of ```make VERBOSE=1``` look like?

**Comment by FIshikawa** [comment]
Thank you, the problem is solved. 
May be, in my environment, I used /opt/materiapps-intel/gcc7/gcc7-7.3.0-1/bin/c+ as CXX compiler and it caused the problem.
